
export default {
  messages: {

    // buttons
    validate: 'Validte',
    save: 'Save',
    cancel: 'Cancel',
    back: 'Back',
    requestNubmer: 'Request Number',

    // General
    home: 'Home',
    privacyStatement: 'Privacy Statement',
    technicalSupport: 'Technical Support',
    callUs: 'Call Us',
    copyright: 'Copyrights for Elm © 2018',
    searchFor: 'Search For',
    waiting: 'Waiting for latitude and longitude !!!',
    view: 'View',
    welcome: 'ًWelcome to Delivery Portal',
    welcomeSmall: 'Welcome',
    purpose: 'A portal to control the activity of transferring goods and delivery',

    // Request Delivery License
    owner: 'Vehicle Owner',
    deliveryActivity: 'Delivery Activity',
    requestLicense: 'Request Delivery License',
    driverType: 'Driver Type',
    seqNoOfVeh: 'Sequence Number of Vehicle Registration',
    ownerId: 'Owner ID',
    coOwner: 'Vehicle Co-Owner',
    authDriver: 'Authorized Driver',
    vMaker: 'Vehicle Maker',
    plateNumber: 'Plate Number',
    color: 'Color',
    plateType: 'Plate Type',
    expiryDate: 'Expiry Date',
    vehicleModel: 'Vehicle Model',
    ownerName: 'Owner Name',
    modelYear: 'Model Year',
    deliveryActivityLicenseNo: 'Delivery Activity License #',
    deliveryActivityLicenseDate: 'Delivery Activity License Date',
    licenseDuration: 'License Duration',
    licenseStartDate: 'License Start Date',
    licenseEndDate: 'License End Date',
    attachment: 'Attachment',
    inYears: 'In Years',
    vehicalModel: 'Vehical model',
    vehicalMaker: 'Vehicle Maker',
    createdAt: 'Created by',
    actions: 'Actions',
    search: 'Search',
    licenseRequestInfo: 'License Request Information',
    sequanceNumber: 'Sequence Number of Vehicle Registration',
    driverId: 'Driver ID',
    authorizedDriver: 'Authorized Driver',
    oneYear: 'One Year',
    carInfo: 'Vehical Details',
    requestInfo: 'Request Informations',
    driverName: 'Driver Name',
    print: 'Print',
    licenseRequestList: 'License Request List',
    licenseRequestManagement: 'License Request List',

    // self registraion
    orgInfo: 'Organization Information',
    userInfo: 'User Information',
    selfRegistraion: 'self Registraion',
    organizationType: 'Organization type',
    registerBy:'Register By',
    organizationId: 'MOI number',
    crNumber: 'CR number',
    crIssueDate: 'CR issue date',
    crEndDate: 'CR expairy date',
    residentsId: 'Residents Id',
    sponsoredNumber: 'Sponsored Number',
    userType: 'User type',
    idNumber: 'ID number',
    birthDate: 'Date of birth',
    email: 'Email',
    mobileNumber: 'Mobile',
    long: 'longitude',
    lat: 'latitude',
    region: 'Region',
    city: 'City',
    district: 'District',
    street: 'Street',
    postalCode: 'Postal code',
    phoneNumber: 'Phone',
    faxNumber: 'Fax',
    government: 'Government',
    company: 'Company',
    corporation: 'Corporation',
    registrationDate: 'Registration Date',
    registrationList: 'Registration List',
    registrationNumber: 'Registration Number',
    agreementForm: 'agreement Form',
    cr: 'Commercial Registration',
    saudi: 'saudi',
    nonsaudi: 'non-saudi',
    IDN: 'Id/Iqama Number',
    registrationInfo: 'Registration Information',
    termsAndConditionMsg: 'Terms and Conditions',
    iqamaId: 'Residence number of one of the sponsors',
    numberOfSponsors:'Number Of sponsors',

    // LocationComponent
    selectAddressFromMap: 'Pick Your location',
    lng: 'Longitude',
    outOfKSA: 'The selected address is outside KSA',
    invalidLocation: 'The selected address is invalid',
    selectAddress: 'Select Address',

    // validation Msgs
    'errorMessage.isRequired': 'Please enter {fieldName}',
    'errorMessage.Invalid': 'Invalid {fieldName}',
    'errorMessage.moiNotValid': 'Invalid MOI number ',
    'errorMessage.ninNotValid': 'ID number must be between 1000000000 and 1999999999',
    'errorMessage.iqamaNotValid': 'ID number must be between 2000000000 and 2999999999',
    'errorMessage.mobileNotValid': 'Please enter a valid mobile number',
    'errorMessage.emailNotValid': 'Please enter a valid email',
    'errorMessage.dateNotValid': 'Invalid date format',
    'errorMessage.HdateNotValid': 'Invalid Hijri date format',
    'errorMessage.arabicLetters': 'Enter Arabic letters',
    'errorMessage.englishLetters': 'Enter English letters',
    'errorMessage.numeric': 'Please enter numeric values',
    'errorMessage.requiredOTP': 'Please enter Verification Code',
    'errorMessage.phoneNumberNotValid': 'Please enter a valid phone number',
    'errorMessage.NinAndIqama': 'Please enter a valid ID number',
    'errorMessage.currentPassword.isRequired': 'Please enter current password',
    'errorMessage.isRequiredOwners': 'Please enter the Corporate owners',
    'errorMessage.RequiredWasel': 'Please select wasel address before continue ',
    'errorMessage.RequiredGMaps': 'Please select branch location in google maps',
    'errorMessage.RequiredBranch': 'Please select branch from list',
    'errorMessage.waybillAlreadyExist': 'Air waybill number already exist.',
    'errorMessage.RequiredItem': 'Please Add Shipment item',
    allFieldsAreRequired: 'All fields are required for this item',
    'errorMessage.RequiredTermsAndCon': 'Please accept the terms and conditions',

    "customers": "Customers",
    "products": "Products",
    "newOrder": "New Order",
    "language": "language",
    "welcomeUser": "Welcome back <b>&nbsp;{user}</b>",
    "logout": "Sign Out",
    "phone": "Phone",
    "birthdate": "Birth date",
    "lastname": "Last Name",
    "firstname": "First Name",
    "id": "ID",
    "addNewCustomer": "Add new Customer",
    "delete": "Delete",
    "edit": "Edit",
    "login": "Login",
    "username": "Username",
    "password": "Password",
    "home": "Home",
    "en": "English",
    "country": "Country",
    "city": "City",
    "save": "Save",
    "back": "Back",
    "next": "Next",
    "editCustomer": "Edit Customer",
    "firstNamerequired": "first name required",
    "lastNamerequired": "last name required",
    "birthdateRequired": "birthdate required",
    "birthdateFormatError" : "birthdate should be in the format dd/MM/yyyy",
    "badCredentials": "Username or password is incorrect",
    "shipmenntOrigin": "Shipmennt Origin",
    "shipmenntDestination": "Shipment Destination  ",
    "pickupAddress":"Pickup Address ",
    "dropOffAddress":"Drop-off Address ",
    "district":"District ",
    "email":"Email",
    "zipCode": "ZIP Code",
    "useDefaultOrigin":"Use Default Address",
    "region":"Region",
    "badCredentials": "Username or password is incorrect",
    "fromCity": "From City",
    "toCity": "To City",
    "badCredentials": "Username or password is incorrect",
    "SATURDAY":"Saturday",
    "SUNDAY":"Sunday",
    "MONDAY":"Monday",
    "TUESDAY":"Tuesday",
    "WEDNESDAY":"Wednesday",
    "THURSDAY":"Thursday",
    "FRIDAY":"Friday",
    "deliveryOn":"Delivery on ",
    "SAR":"SR",
    requestNewShipment:'Request new Shipment',
    shipmentList:'Shipment List',
    getRate:'Get rate',
    shipNow:'Ship Now!',
    selectShippingCompany:'Select Shipping Company',
    shippingCompanies:'Shipping Companies',
  },
}
